"""
XLSX export (Pipeline B — structured data extraction, spec sections 13/17).

Reads the same Document JSON IR the PDF/DOCX exporters read (never Excel
from raw OCR text, never re-derived from the PDF) and produces a workbook
of actual structured tables -- never one giant OCR-text cell. One sheet per
detected table (`Table_001`, `Table_002`, ...), plus a `Document_Info`
cover sheet and a `Table_Index` sheet linking every table sheet back to its
source page, detected title, and detection confidence.

Numeric integrity is the overriding priority (spec section 47): every cell
is written as the OCR'd text verbatim, never coerced to a numeric type or
"corrected" -- "33,541" stays the string "33,541", not reparsed into a
float that could silently normalize or corrupt it (e.g. drop a leading
zero, misread a comma). Cosmetic right-alignment is applied to
numeric-looking text for readability; the underlying value never changes.
"""
from __future__ import annotations

import io
import re

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

from app.core.logging import get_logger
from app.models.enums import LayoutBlockType, TextAlign
from app.schemas.document_json import DocumentBlockJSON, PageJSON

logger = get_logger(__name__)

_NUMERIC_RE = re.compile(r"^[+-]?[\d,]*\.?\d+%?$")

_HEADER_FILL = PatternFill(start_color="DCE6F1", end_color="DCE6F1", fill_type="solid")
_HEADER_FONT = Font(bold=True)
_TITLE_FONT = Font(bold=True, size=13)
_THIN_BORDER = Border(*(Side(style="thin", color="B7B7B7") for _ in range(4)))
_MAX_COL_WIDTH = 48
_MIN_COL_WIDTH = 8
_EXCEL_ALIGN = {
    TextAlign.LEFT: "left",
    TextAlign.CENTER: "center",
    TextAlign.RIGHT: "right",
}


def render_document_excel(pages: list[PageJSON], source_filename: str = "") -> bytes:
    wb = Workbook()
    info_sheet = wb.active
    info_sheet.title = "Document_Info"

    index_sheet = wb.create_sheet("Table_Index")
    _write_index_header(index_sheet)

    table_count = 0
    index_row = 2
    for page_json in pages:
        for block in page_json.sorted_blocks():
            if block.type != LayoutBlockType.TABLE or not block.table or not block.table.rows:
                continue
            table_count += 1
            sheet_name = f"Table_{table_count:03d}"
            title = _derive_table_title(page_json, block, table_count)
            try:
                sheet = wb.create_sheet(sheet_name)
                n_rows, n_cols = _write_table_sheet(sheet, block, page_json, title)
            except Exception as exc:  # noqa: BLE001 - one bad table must not fail the whole export
                logger.warning("excel_table_render_failed", page=page_json.page_number, table_index=table_count, error=str(exc))
                continue

            index_sheet.cell(row=index_row, column=1, value=table_count)
            index_sheet.cell(row=index_row, column=2, value=sheet_name)
            index_sheet.cell(row=index_row, column=3, value=title)
            index_sheet.cell(row=index_row, column=4, value=page_json.page_number)
            index_sheet.cell(row=index_row, column=5, value=round(block.confidence, 3))
            index_sheet.cell(row=index_row, column=6, value=n_rows)
            index_sheet.cell(row=index_row, column=7, value=n_cols)
            index_row += 1

    _write_info_sheet(info_sheet, pages, source_filename, table_count)
    _finalize_index_sheet(index_sheet, index_row - 1)

    buffer = io.BytesIO()
    wb.save(buffer)
    return buffer.getvalue()


def _write_info_sheet(sheet: Worksheet, pages: list[PageJSON], source_filename: str, table_count: int) -> None:
    sheet.column_dimensions["A"].width = 28
    sheet.column_dimensions["B"].width = 50
    rows = [
        ("Source document", source_filename or "-"),
        ("Total pages", len(pages)),
        ("Tables extracted", table_count),
        ("Generated by", "Document Clean & Reconstruct AI"),
    ]
    sheet.cell(row=1, column=1, value="Document Info").font = _TITLE_FONT
    for i, (label, value) in enumerate(rows, start=3):
        sheet.cell(row=i, column=1, value=label).font = _HEADER_FONT
        sheet.cell(row=i, column=2, value=value)


def _write_index_header(sheet: Worksheet) -> None:
    headers = ["#", "Sheet", "Table Title", "Source Page", "Confidence", "Rows", "Columns"]
    for col, h in enumerate(headers, start=1):
        cell = sheet.cell(row=1, column=col, value=h)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL


def _finalize_index_sheet(sheet: Worksheet, last_row: int) -> None:
    widths = [6, 12, 40, 12, 12, 8, 10]
    for i, w in enumerate(widths, start=1):
        sheet.column_dimensions[get_column_letter(i)].width = w
    if last_row >= 1:
        sheet.freeze_panes = "A2"
        sheet.auto_filter.ref = f"A1:G{max(last_row, 1)}"


def _derive_table_title(page_json: PageJSON, table_block: DocumentBlockJSON, table_number: int) -> str:
    """Uses the nearest preceding heading/paragraph on the same page (by
    z_order) as a human-readable title when one exists, matching how a
    reader would identify "the table under this heading" -- falls back to
    a page-qualified generic name rather than inventing content."""
    candidates = [
        b for b in page_json.blocks
        if b.z_order < table_block.z_order
        and b.type in (LayoutBlockType.HEADING, LayoutBlockType.SUBHEADING, LayoutBlockType.TITLE)
        and b.content
    ]
    if candidates:
        nearest = max(candidates, key=lambda b: b.z_order)
        text = " ".join(run.text for run in nearest.content).strip()
        if text:
            return text[:80]
    return f"Table {table_number} (Page {page_json.page_number})"


def _write_table_sheet(sheet: Worksheet, table_block: DocumentBlockJSON, page_json: PageJSON, title: str) -> tuple[int, int]:
    table = table_block.table
    n_rows = len(table.rows)
    n_cols = max((c.column + c.colspan for r in table.rows for c in r.cells), default=0)
    if n_rows == 0 or n_cols == 0:
        return 0, 0

    header_offset = 3  # title row + source-page row + blank row
    sheet.cell(row=1, column=1, value=title).font = _TITLE_FONT
    sheet.cell(row=2, column=1, value=f"Source page: {page_json.page_number}    Detection confidence: {round(table_block.confidence, 3)}").font = Font(italic=True, size=9)

    merged: set[tuple[int, int]] = set()
    for row in table.rows:
        for cell in row.cells:
            if cell.row >= n_rows or cell.column >= n_cols:
                continue
            excel_row = header_offset + cell.row + 1
            excel_col = cell.column + 1
            xl_cell = sheet.cell(row=excel_row, column=excel_col, value=cell.text)
            xl_cell.border = _THIN_BORDER
            if cell.is_header or cell.row == 0:
                xl_cell.font = _HEADER_FONT
                xl_cell.fill = _HEADER_FILL
            align_horizontal = "right" if _NUMERIC_RE.match(cell.text.strip()) else _EXCEL_ALIGN.get(cell.align_h, "left")
            xl_cell.alignment = Alignment(horizontal=align_horizontal, vertical="center", wrap_text=True)

            if cell.rowspan > 1 or cell.colspan > 1:
                r1, c1 = excel_row, excel_col
                r2 = min(header_offset + cell.row + cell.rowspan, header_offset + n_rows)
                c2 = min(cell.column + cell.colspan, n_cols) + 1
                if (r2, c2) != (r1, c1) and (r1, c1) not in merged:
                    try:
                        sheet.merge_cells(start_row=r1, start_column=c1, end_row=r2, end_column=c2 - 1)
                        merged.add((r1, c1))
                    except Exception:  # noqa: BLE001 - overlapping merge ranges must not fail the export
                        pass

    for col in range(1, n_cols + 1):
        max_len = 0
        for row_cells in table.rows:
            for c in row_cells.cells:
                if c.column + 1 == col:
                    max_len = max(max_len, len(c.text))
        sheet.column_dimensions[get_column_letter(col)].width = max(_MIN_COL_WIDTH, min(_MAX_COL_WIDTH, max_len + 4))

    sheet.freeze_panes = sheet.cell(row=header_offset + 2, column=1).coordinate
    last_row = header_offset + n_rows
    sheet.auto_filter.ref = f"A{header_offset + 1}:{get_column_letter(n_cols)}{last_row}"
    return n_rows, n_cols
